AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance Example

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      KeyName: myKeyPair
      SecurityGroups:
        - Ref: MySecurityGroup

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0

  MyKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: myKeyPair
      PublicKeyMaterial: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwYAUrHCvNw8MXdcP4W8d
        GFi1BiLC...
        -----END PUBLIC KEY-----
